import {calculate} from './finance.js';
const securities={NVDA:{name:'NVIDIA',ipo:'1999-01-22',start:3.9,end:118.2,growth:[1,1.6,.7,4,7,18,40,92,180,350]},AAPL:{name:'Apple',ipo:'1980-12-12',start:5.1,end:208,growth:[1,.8,2,9,18,26,58,110,160,210]},MSFT:{name:'Microsoft',ipo:'1986-03-13',start:29,end:512,growth:[1,.7,1,2,4,8,14,22,30,38]},AMZN:{name:'Amazon',ipo:'1997-05-15',start:4.5,end:230,growth:[1,.3,1.4,5,18,34,60,90,120,140]},SPY:{name:'S&P 500',ipo:'1993-01-29',start:145,end:650,growth:[1,.8,1.1,1.4,2,2.8,3.5,4.2,5,5.8]}};
let mode='price',lastResult=null,showReal=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const symbols={CNY:'¥',USD:'$',JPY:'¥',EUR:'€'};const fmt=(v,c=$('#currency').value)=>new Intl.NumberFormat(navigator.language,{style:'currency',currency:c,maximumFractionDigits:0}).format(v);const pct=v=>new Intl.NumberFormat(navigator.language,{style:'percent',maximumFractionDigits:1,signDisplay:'always'}).format(v);
function scenario(){const sec=securities[$('#ticker').value],cur=$('#currency').value;const fx={CNY:[7.12,7.18],USD:[1,1],JPY:[108,147],EUR:[.96,.86]}[cur];return {amount:+$('#amount').value,date:$('#date').value,endDate:'2026-08-26',ipo:sec.ipo,startFx:fx[0],endFx:fx[1],startPrice:sec.start,endPrice:sec.end,fractional:$('#fractional').checked,mode,adjustedPrices:true,splits:[],dividends:mode==='total'?[{amount:.32,reinvestmentPrice:70}]:[],cpiStart:100,cpiEnd:153.4,sec,cur}}
function metric(label,value,note=''){return `<div class="metric"><small>${label}</small><strong>${value}</strong>${note?`<span>${note}</span>`:''}</div>`}
function render(){try{const s=scenario(),r=calculate(s);lastResult={s,r};$('#result').hidden=false;$('#todayValue').textContent=fmt(r.current);$('#summary').textContent=`${fmt(s.amount)} invested in ${s.sec.name} · ${r.years.toFixed(1)} years in the market`;
 $('#thenMetrics').innerHTML=metric('STARTING CAPITAL',fmt(s.amount))+metric('TRADING SESSION',s.date,'Selected demo session')+metric('USD CONVERSION',fmt(r.usd,'USD'),`${s.startFx.toFixed(4)} ${s.cur}/USD`)+metric('SHARES ACQUIRED',r.shares.toLocaleString(undefined,{maximumFractionDigits:4}),s.fractional?'Fractional shares enabled':'Whole shares only');
 $('#resultMetrics').innerHTML=metric('TOTAL PROFIT',fmt(r.profit))+metric('TOTAL RETURN',pct(r.totalReturn))+metric('ANNUALIZED RETURN',pct(r.cagr))+metric('INVESTMENT MULTIPLE',`${r.multiple.toFixed(1)}×`);
 $('#driverBars').innerHTML=[['Stock appreciation',Math.min(100,(s.endPrice/s.startPrice)*2)],['Currency movement',Math.min(100,Math.abs(s.endFx/s.startFx-1)*300)],['Dividend effect',mode==='total'?18:0],['Inflation drag',(r.inflationFactor-1)*100]].map(([n,v])=>`<div class="driver"><label><span>${n}</span><span>${n==='Inflation drag'?'-':''}${Number(v).toFixed(1)}%</span></label><div class="bar"><i style="width:${Math.max(1,v)}%"></i></div></div>`).join('');
 $('#calculationDetails').innerHTML=`<p><b>Price treatment</b><br>Adjusted demo price; splits are not applied again.</p><p><b>FX treatment</b><br>${s.startFx.toFixed(4)} at purchase → ${s.endFx.toFixed(4)} today.</p><p><b>Inflation treatment</b><br>Illustrative CPI factor ${r.inflationFactor.toFixed(3)}; real value ${fmt(r.realValue)}.</p><p><b>Dividend treatment</b><br>${mode==='total'?'Illustrative reinvestment enabled.':'Excluded for price return.'}</p><p><b>Residual cash</b><br>${fmt(r.cashUsd,'USD')}</p><p><b>Source</b><br>Bundled development adapter · not live market data.</p>`;drawChart(s.sec.growth,r);location.hash='result';setTimeout(()=>$('#result').scrollIntoView({behavior:'smooth'}),50)}catch(e){alert(e.message)}}
function drawChart(values,r){const svg=$('#chart'),max=Math.max(...values),min=Math.min(...values);const pts=values.map((v,i)=>{const adjusted=showReal?v/(1+i*.045):v;return [40+i*920/(values.length-1),360-(adjusted-min)/(max-min)*310]});const d=pts.map((p,i)=>(i?'L':'M')+p.join(',')).join(' ');svg.innerHTML=`<defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#c5ff4a" stop-opacity=".26"/><stop offset="1" stop-color="#c5ff4a" stop-opacity="0"/></linearGradient></defs>${[50,150,250,350].map(y=>`<line class="gridline" x1="30" x2="970" y1="${y}" y2="${y}"/>`).join('')}<path class="chart-fill" d="${d}L960,370L40,370Z"/><path class="chart-line" d="${d}"/>${pts.map(p=>`<circle class="chart-dot" cx="${p[0]}" cy="${p[1]}" r="4"/>`).join('')}`}
$('#composer').addEventListener('submit',e=>{e.preventDefault();render()});$$('[data-mode]').forEach(b=>b.onclick=()=>{$$('[data-mode]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');mode=b.dataset.mode});$('#currency').onchange=e=>$('.currency-mark').textContent=symbols[e.target.value];
function switchView(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.view===id));scrollTo(0,0);history.replaceState(null,'','#'+id)}$$('[data-view]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();switchView(b.dataset.view)}));
$('#theme').onclick=()=>{const d=document.documentElement;d.dataset.theme=d.dataset.theme==='dark'?'light':'dark';localStorage.setItem('then-now-theme',d.dataset.theme)};document.documentElement.dataset.theme=localStorage.getItem('then-now-theme')||'light';$('#lang').onclick=()=>alert('简体中文 localization is architected for the verified-data release.');
$('#copy').onclick=async()=>{const u=new URL(location.href);u.pathname=`/simulate/${$('#ticker').value}`;u.search=`?date=${$('#date').value}&amount=${$('#amount').value}&currency=${$('#currency').value}`;await navigator.clipboard.writeText(u.href);$('#copy').textContent='✓ LINK COPIED'};$('#save').onclick=()=>{localStorage.setItem('then-now-saved',JSON.stringify({ticker:$('#ticker').value,date:$('#date').value,amount:$('#amount').value,currency:$('#currency').value}));$('#save').textContent='♥ SAVED'};
$('#realToggle').onclick=()=>{showReal=!showReal;$('#realToggle').classList.toggle('selected',showReal);if(lastResult)drawChart(lastResult.s.sec.growth,lastResult.r)};$('#logToggle').onclick=()=>alert('Log scale requires a verified daily price series.');$$('[data-scenario]').forEach(b=>b.onclick=()=>{const [d,t]=b.dataset.scenario.split(',');$('#date').value=d;$('#ticker').value=t;scrollTo({top:0,behavior:'smooth'})});
const path=location.pathname.match(/\/simulate\/([^/]+)/);if(path&&securities[path[1]]){const q=new URLSearchParams(location.search);$('#ticker').value=path[1];$('#date').value=q.get('date')||$('#date').value;$('#amount').value=q.get('amount')||$('#amount').value;$('#currency').value=q.get('currency')||'CNY';render()}
